// Package v1_21_4 - Auto-generated packet IDs for Minecraft 1.21.4
// Code generated by tools/mcproto; DO NOT EDIT.

package v1_21_4

const (
	// handshake_serverbound
	sHandshake PacketID = 0x00

	// status_serverbound
	sStatusRequest PacketID = 0x00
	sStatusPing PacketID = 0x01

	// status_clientbound
	cStatusResponse PacketID = 0x00
	cStatusPong PacketID = 0x01

	// configuration_serverbound
	sConfigAck PacketID = 0x00
	sConfigPluginResponse PacketID = 0x01

	// configuration_clientbound
	cConfigPluginRequest PacketID = 0x00
	cConfigDisconnect PacketID = 0x01
	cFinishConfiguration PacketID = 0x02
	cConfigKeepAlive PacketID = 0x03
	cConfigSyncData PacketID = 0x04

	// login_serverbound
	sLoginStart PacketID = 0x00
	sEncryptionResponse PacketID = 0x01
	sLoginPluginResponse PacketID = 0x02

	// login_clientbound
	cLoginDisconnect PacketID = 0x00
	cLoginSuccess PacketID = 0x02
	cSetCompression PacketID = 0x03
	cLoginPluginRequest PacketID = 0x04

	// play_serverbound
	sKeepAlive PacketID = 0x18
	sChatMessage PacketID = 0x05
	sPlayerPosition PacketID = 0x1A
	sPlayerPositionRotation PacketID = 0x1B
	sPlayerRotation PacketID = 0x1C
	sPlayerMovement PacketID = 0x1D
	sClientCommand PacketID = 0x07
	sPluginMessage PacketID = 0x11

	// play_clientbound
	cKeepAlive PacketID = 0x26
	cJoinGame PacketID = 0x2E
	cChatMessage PacketID = 0x37
	cSystemChat PacketID = 0x66
	cDisconnect PacketID = 0x1D
	cPluginMessage PacketID = 0x25
	cServerData PacketID = 0x47
	cRespawn PacketID = 0x44
	cChunkData PacketID = 0x24
	cChunkDataUpdate PacketID = 0x5B
	cBlockUpdate PacketID = 0x0A
	cPlayerInfo PacketID = 0x3D
	cPlayerInfoRemove PacketID = 0x42
	cSynchronizePosition PacketID = 0x40
	cUpdateRecipes PacketID = 0x7E

)

type PacketID int32
