// mcproto is a code generator that automatically produces Minecraft protocol packet IDs.
//
// Usage:
//
//	cd tools/mcproto
//	go run main.go -version 1.21.4
//
// This tool downloads the Minecraft server JAR, extracts packet IDs from the
// protocol class files, and generates Go packet ID constants.
// If JAR download/extraction fails, it falls back to built-in definitions.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
)

type PacketDef struct {
	Name    string
	ID      int32
	State   string
	Bound   string // serverbound / clientbound
}

func main() {
	version := flag.String("version", "1.21.4", "Minecraft version")
	output := flag.String("output", "", "Output file path")
	flag.Parse()

	packets := getDefinitions(*version)

	if *output == "" {
		pkgDir := fmt.Sprintf("../../protocol/packetid/v%s", strings.ReplaceAll(*version, ".", "_"))
		os.MkdirAll(pkgDir, 0755)
		*output = fmt.Sprintf("%s/types.go", pkgDir)
	}

	generate(packets, *version, *output)
	fmt.Printf("Generated %d packet IDs for Minecraft %s -> %s\n", len(packets), *version, *output)
}

func getDefinitions(version string) []PacketDef {
	packets, err := extractPacketIDs(version)
	if err != nil {
		fmt.Fprintf(os.Stderr, "JAR extraction failed (%v); using fallback definitions\n", err)
		return fallbackDefinitions()
	}
	if len(packets) == 0 {
		fmt.Fprintf(os.Stderr, "No packets extracted from JAR; using fallback definitions\n")
		return fallbackDefinitions()
	}
	return packets
}

func generate(packets []PacketDef, version, output string) {
	var sb strings.Builder

	pkgName := fmt.Sprintf("v%s", strings.ReplaceAll(version, ".", "_"))
	pkgName = strings.ReplaceAll(pkgName, "-", "_")

	sb.WriteString(fmt.Sprintf("// Package %s - Auto-generated packet IDs for Minecraft %s\n", pkgName, version))
	sb.WriteString("// Code generated by tools/mcproto; DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

	sb.WriteString("const (\n")

	groups := make(map[string][]PacketDef)
	for _, p := range packets {
		key := p.State + "_" + p.Bound
		groups[key] = append(groups[key], p)
	}

	for key, defs := range groups {
		sb.WriteString(fmt.Sprintf("\t// %s\n", key))
		for _, d := range defs {
			constName := fmt.Sprintf("%s%s", d.Bound[:1], d.Name)
			sb.WriteString(fmt.Sprintf("\t%s PacketID = 0x%02X\n", constName, d.ID))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(")\n\n")
	sb.WriteString("type PacketID int32\n")

	if err := os.WriteFile(output, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", output, err)
		os.Exit(1)
	}
}



