// Package packetid contains Minecraft protocol packet ID constants.
// These constants will be auto-generated by the tools/mcproto code generator.
// Currently, basic hand-written constants are available.
package packetid
